task_manager/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePageView
from task_manager.users import views as userViews
from task_manager.statuses import views as statusViews
from task_manager.tasks import views as taskViews
from task_manager.labels import views as labelViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='main_page'),
    path('users/', userViews.IndexView.as_view(), name='users'),
    path(
        'users/create/', 
        userViews.RegistrationView.as_view(), 
        name='create_user'),
    path('login/', userViews.LoginUserView.as_view(), name='login'),
    path('logout/', userViews.LogoutUserView.as_view()),
    path(
        'users/<int:user_id>/update/',
        userViews.UserEditView.as_view(),
        name='edit_user'),
    path(
        'users/<int:user_id>/delete/',
        userViews.UserDeleteView.as_view(),
        name='delete_user'),
    path('statuses/', statusViews.StatusView.as_view(), name='statuses'),
    path('statuses/create/', statusViews.CreateStatusView.as_view()),
    path(
        'statuses/<int:status_id>/update/',
        statusViews.EditStatusView.as_view(),
        name='edit_status'),
    path(
        'statuses/<int:status_id>/delete/',
        statusViews.StatusDeleteView.as_view(),
        name='delete_status'),
    path('tasks/', taskViews.TaskView.as_view(), name='tasks'),
    path(
        'tasks/<int:task_id>/', 
        taskViews.ShowTaskView.as_view(), 
        name='task'),
    path(
        'tasks/create/', 
        taskViews.CreateTaskView.as_view(), 
        name='tasks_create'),
    path(
        'tasks/<int:task_id>/update/',
        taskViews.EditTaskView.as_view(),
        name='edit_task'),
    path(
        'tasks/<int:task_id>/delete/',
        taskViews.DeleteTaskView.as_view(),
        name='delete_task'
        ),
    path('labels/', labelViews.LabelsView.as_view(), name='labels'),
    path(
        'labels/create/', 
        labelViews.CreateLabelView.as_view(), 
        name='create_label'),
    path(
        'labels/<int:label_id>/update/',
        labelViews.EditLabelView.as_view(),
        name='edit_label'
        ),
    path(
        'labels/<int:label_id>/delete/',
        labelViews.DeleteLabelView.as_view(),
        name='delete_label'
        ),
]

task/models.py
from django.db import models
from django.contrib.auth.models import User
from status.models import Status
from label.models import Label

class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(
        User, 
        on_delete=models.PROTECT,
        related_name='authored_tasks'
    )
    executor = models.ForeignKey(
        User, 
        on_delete=models.PROTECT,
        null=True, 
        blank=True, 
        related_name='executed_tasks'
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name='task_set'
    )
    labels = models.ManyToManyField(
        Label,
        related_name='tasks',
        blank=True,
        verbose_name='Метки'
    )
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms
from .models import Label


class LabelForm(forms.ModelForm):
    name = forms.CharField(
        label="Имя", 
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': "Имя",
        }

task_manager/labels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, View, UpdateView
from .forms import LabelForm
from .models import Label
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import ProtectedError


class LabelsView(ListView):
    model = Label
    template_name = 'label/index.html'
    context_object_name = 'labels'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Label.objects.annotate().values(
            'id', 
            'name', 
            'time_create',
        ).order_by('time_create')


class CreateLabelView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = LabelForm()
        return render(request, 'label/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = LabelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Метка успешно создана')
            return redirect('labels')
        return render(request, 'label/create.html', {'form': form})
    

class EditLabelView(UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'label/edit.html'
    pk_url_kwarg = 'label_id'
    success_url = reverse_lazy('labels')
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        label = super().get_object(queryset)
        return label
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object is None:
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object is None:
            return redirect(self.success_url)
        messages.success(request, 'Метка успешно изменена')
        return super().post(request, *args, **kwargs)
    

class DeleteLabelView(View):
    success_url = reverse_lazy('labels')
    template_name = 'label/label_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        label_id = self.kwargs.get('label_id')
        return get_object_or_404(Label, pk=label_id)

    def get(self, request, *args, **kwargs):
        label_to_delete = self.get_object()
        return render(request, self.template_name, {'label': label_to_delete})

    def post(self, request, *args, **kwargs):
        label_to_delete = self.get_object()
        try:
            label_to_delete.delete()
            messages.success(request, 'Метка успешно удалена')
            return redirect(self.success_url)
        except ProtectedError:
            messages.error(
                request, 
                'Невозможно удалить метку, потому что она используется'
                )
            return redirect('labels')

task_manager/statuses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, View, UpdateView
from .forms import StatusForm
from .models import Status
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import ProtectedError


class StatusView(ListView):
    model = Status
    template_name = 'status/index.html'
    context_object_name = 'statuses'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Status.objects.annotate().values(
            'id', 
            'name', 
            'time_create',
        ).order_by('time_create')


class CreateStatusView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = StatusForm()
        return render(request, 'status/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Статус успешно создан')
            return redirect('statuses')
        return render(request, 'status/create.html', {'form': form})
    

class EditStatusView(UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'status/edit.html'
    pk_url_kwarg = 'status_id'
    success_url = reverse_lazy('statuses')
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        status = super().get_object(queryset)
        return status
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object is None:
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object is None:
            return redirect(self.success_url)
        messages.success(request, 'Статус успешно изменен')
        return super().post(request, *args, **kwargs)
    

class StatusDeleteView(View):
    success_url = reverse_lazy('statuses')
    template_name = 'status/status_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        status_id = self.kwargs.get('status_id')
        return get_object_or_404(Status, pk=status_id)

    def get(self, request, *args, **kwargs):
        status_to_delete = self.get_object()
        return render(
            request, 
            self.template_name, 
            {'status': status_to_delete}
            )

    def post(self, request, *args, **kwargs):
        status_to_delete = self.get_object()
        try:
            status_to_delete.delete()
            messages.success(request, 'Статус успешно удален')
            return redirect(self.success_url)
        except ProtectedError:
            messages.error(
                request, 
                'Невозможно удалить статус, потому что он используется'
                )
            return redirect('statuses')

task_manager/tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, View, UpdateView
from .forms import TaskForm, TaskFilterForm
from .models import Task
from django.urls import reverse_lazy
from django.contrib import messages


class TaskView(ListView):
    model = Task
    template_name = 'task/index.html'
    context_object_name = 'tasks'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request,
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Task.objects.select_related(
            'status',
            'author',
            'executor'
            ).order_by('time_create')
        status = self.request.GET.get('status')
        executor = self.request.GET.get('executor')
        label = self.request.GET.get('label')
        self_tasks = self.request.GET.get('self_tasks')

        if status and status != '':
            queryset = queryset.filter(status_id=int(status))

        if executor is not None:
            if executor and executor != '':
                queryset = queryset.filter(executor_id=int(executor))

        if label and label != '':
            queryset = queryset.filter(labels__id=label).distinct()

        if self_tasks and self_tasks.lower() in ['true', 'on', '1', 'yes']:
            queryset = queryset.filter(author=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = TaskFilterForm(self.request.GET)
        return context


class CreateTaskView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        form = TaskForm(user=request.user)
        return render(request, 'task/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Задача успешно создана')
            return redirect('tasks')
        return render(request, 'task/create.html', {'form': form})


class ShowTaskView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get_object(self):
        task_id = self.kwargs.get('task_id')
        return get_object_or_404(Task, pk=task_id)

    def get(self, request, *args, **kwargs):
        task_to_show = self.get_object()
        return render(request, 'task/show_task.html', {'task': task_to_show})


class EditTaskView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/edit.html'
    pk_url_kwarg = 'task_id'
    success_url = reverse_lazy('tasks')
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request,
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        messages.success(self.request, 'Задача успешно изменена')
        return super().form_valid(form)


class DeleteTaskView(View):
    success_url = reverse_lazy('tasks')
    template_name = 'task/task_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, 
                'Вы не авторизованы! Пожалуйста, войдите в систему.'
                )
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        task_id = self.kwargs.get('task_id')
        return get_object_or_404(Task, pk=task_id)

    def get(self, request, *args, **kwargs):
        task_to_delete = self.get_object()
        if request.user.id != task_to_delete.author.id:
            messages.error(request, 'Задачу может удалить только ее автор')
            return redirect(self.success_url)
        return render(request, self.template_name, {'task': task_to_delete})

    def post(self, request, *args, **kwargs):
        task_to_delete = self.get_object()
        if request.user.id != task_to_delete.author.id:
            messages.error(request, 'Задачу может удалить только ее автор')
            return redirect(self.success_url)
        task_to_delete.delete()
        messages.success(request, 'Задача успешно удалена')
        return redirect(self.success_url)

task_manager/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):

    def get(self, request):
        return render(request, 'index.html')

task_manager/templates/task/create.html
{% extends 'base.html' %}
{% block content %}

<div class="container wrapper flex-grow-1">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <h1 class="my-4">Создание задачи</h1>
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <div class="mb-3">
                    <label for="{{ form.name.id_for_label }}" class="form-label">Имя</label>
                    {{ form.name }}
                    <div class="invalid-feedback">
                        {{ form.name.errors }}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
                    {{ form.description }}
                    <div class="invalid-feedback">
                        {{ form.description.errors }}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="{{ form.status.id_for_label }}" class="form-label">Статус</label>
                    {{ form.status }}
                    <div class="invalid-feedback">
                        {{ form.status.errors }}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="{{ form.executor.id_for_label }}" class="form-label">Исполнитель</label>
                    {{ form.executor }}
                    <div class="invalid-feedback">
                        {{ form.executor.errors }}
                    </div>
                </div>
                <div class="mb-4">
                    <label for="id_labels" class="form-label">Метки</label>
                    <select name="labels" id="id_labels" class="form-select" multiple size="4">
                        {% for label in form.labels.field.queryset %}
                        <option value="{{ label.pk }}">{{ label.name }}</option>
                        {% endfor %}
                    </select>
                    <div class="form-text">Для выбора нескольких меток удерживайте Ctrl (Windows) или Command (Mac)</div>
                </div>
                <div class="d-grid gap-2">
                    <button class="btn btn-primary btn-lg" type="submit">Создать</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

task_manager/templates/task/edit.html
{% extends 'base.html' %}
{% block content %}

<div class="container wrapper flex-grow-1 mt-4">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h2 class="mb-0">Редактирование задачи</h2>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_name" class="form-label fw-bold">Имя</label>
                    <input type="text" class="form-control" id="id_name" name="name" 
                           value="{{ form.name.value|default_if_none:'' }}" required>
                    {% if form.name.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.name.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_description" class="form-label fw-bold">Описание</label>
                    <textarea class="form-control" id="id_description" name="description" 
                              rows="4">{{ form.description.value|default_if_none:'' }}</textarea>
                    {% if form.description.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.description.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_status" class="form-label fw-bold">Статус</label>
                        {{ form.status }}
                        {% if form.status.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.status.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        <label for="id_executor" class="form-label fw-bold">Исполнитель</label>
                        {{ form.executor }}
                        {% if form.executor.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.executor.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="mb-4">
                    <label for="id_labels" class="form-label fw-bold">Метки</label>
                    <select name="labels" id="id_labels" class="form-select" multiple size="4">
                        {% for label in form.labels.field.queryset %}
                        <option value="{{ label.pk }}" {% if label.id in form.labels.value %}selected{% endif %}>{{ label.name }}</option>
                        {% endfor %}
                    </select>
                    <small class="form-text text-muted">
                        Для выбора нескольких меток удерживайте Ctrl (Windows) или Command (Mac)
                    </small>
                    {% if form.labels.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.labels.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <a href="{% url 'tasks' %}" class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-left"></i>Отмена
                    </a>
                    <input class="btn btn-primary" type="submit" value="Изменить">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

task_manager/templates/task/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container wrapper flex-grow-1">
    <div class="modal modal-sheet position-static d-block  p-4 py-md-4" tabindex="-1" role="dialog" id="modalSignin">
        {% if messages %}
        <div class="mb-4">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <div class="">
            <h1 class="my-6">Задачи</h1>
            <a href="/tasks/create/"><button type="button" class="btn btn-outline-primary me-2 mb-3">Создать
                    задачу</button></a>
        </div>

        <div class="card mb-4">
            <div class="card-body">
                <form method="get" class="row g-3">
                    <div class="col-md-3">
                        <label for="{{ filter_form.status.id_for_label }}" class="form-label">
                            {{ filter_form.status.label }}
                        </label>
                        {{ filter_form.status }}
                    </div>
                    <div class="col-md-3">
                        <label for="{{ filter_form.executor.id_for_label }}" class="form-label">
                            {{ filter_form.executor.label }}
                        </label>
                        {{ filter_form.executor }}
                    </div>
                    <div class="col-md-3">
                        <label for="{{ filter_form.label.id_for_label }}" class="form-label">
                            {{ filter_form.label.label }}
                        </label>
                        {{ filter_form.label }}
                    </div>
                    <div class="col-md-3">
                        <div class="form-check mt-4 pt-3">
                            {{ filter_form.self_tasks }}
                            <label for="{{ filter_form.self_tasks.id_for_label }}" class="form-check-label">
                                {{ filter_form.self_tasks.label }}
                            </label>
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Показать</button>
                        <a href="{% url 'tasks' %}" class="btn btn-outline-secondary">Сбросить</a>
                    </div>
                </form>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Статус</th>
                    <th>Автор</th>
                    <th>Исполнитель</th>
                    <th>Дата создания</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                    <td>{{ task.id }}</td>
                    <td><a href="/tasks/{{ task.id }}">{{ task.name }}</a></td>
                    <td>{{ task.status.name }}</td>
                    <td>{{ task.author.first_name }} {{ task.author.last_name }}</td>
                    <td>
                        {% if task.executor %}
                        {{ task.executor.first_name }} {{ task.executor.last_name }}
                        {% else %}
                        Не назначен
                        {% endif %}
                    </td>
                    <td>{{ task.time_create|date:"d.m.Y H:i" }}</td>
                    <td>
                        <a href="/tasks/{{ task.id }}/update/">Изменить</a>
                        <br>
                        <a href="/tasks/{{ task.id }}/delete/">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

task_manager/templates/task/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container wrapper flex-grow-1">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="modal modal-sheet position-static d-block  p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="">
            <h1 class="my-4">Удаление Зачади</h1>
            <form method="post">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить задачу {{ task.name }}?</p>
                <button type="submit" class="btn btn-danger">Да, удалить</button>
                <a href="{% url 'tasks' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}